### ISSUE TITLE
PyCaribean webpage slider header

### ISSUE THREAD

**Issue by r0nni3** [pycaribbean/pycaribbean.github.io#26]
The Heading of the slide is overlapping the image. `left` property of `.activity-slider h3` should be revised.

<img width="931" alt="screen shot 2018-11-29 at 10 39 52 pm" src="https://user-images.githubusercontent.com/1497625/49265322-06844100-f428-11e8-8ee1-51dd3318daa4.png">

<img width="353" alt="screen shot 2018-11-29 at 10 40 08 pm" src="https://user-images.githubusercontent.com/1497625/49265335-113ed600-f428-11e8-909f-fbf7e89dc845.png">

**Comment by Jeanluis019** [comment]
The following pull request solves this issue.
[Fix bad header title in slider #32](https://github.com/pycaribbean/pycaribbean.github.io/pull/32)

@xpostudio4 @emilioferreyra @wm3ndez Please consider closing this issue.

**Comment by emilioferreyra** [comment]
Bug fixed by [Fix bad header title in slider #32](https://github.com/pycaribbean/pycaribbean.github.io/pull/32) confirmed.

Good job @Jeanluis019

**Comment by emilioferreyra** [comment]
Thanks for your report @r0nni3 
We look forward to seeing you in PyCaribbean 2019
